## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
y1_index, y0_index = np.where(y==1)[0], np.where(y==0)[0] 

In [5]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X[y1_index], y[y1_index], test_size=10)
X0_train, X0_test, y0_train, y0_test = train_test_split(X[y0_index], y[y0_index], test_size=10)

In [6]:
x_train, y_train = np.concatenate([X1_train, X0_train]), np.concatenate([y1_train, y0_train])

In [7]:
x_test, y_test = np.concatenate([X1_test, X0_test]), np.concatenate([y1_test, y0_test])

In [8]:
x_test

array([[ 10,  11,  12,  13,  14],
       [135, 136, 137, 138, 139],
       [ 45,  46,  47,  48,  49],
       [180, 181, 182, 183, 184],
       [100, 101, 102, 103, 104],
       [115, 116, 117, 118, 119],
       [105, 106, 107, 108, 109],
       [ 75,  76,  77,  78,  79],
       [130, 131, 132, 133, 134],
       [185, 186, 187, 188, 189],
       [685, 686, 687, 688, 689],
       [500, 501, 502, 503, 504],
       [655, 656, 657, 658, 659],
       [850, 851, 852, 853, 854],
       [865, 866, 867, 868, 869],
       [910, 911, 912, 913, 914],
       [465, 466, 467, 468, 469],
       [335, 336, 337, 338, 339],
       [365, 366, 367, 368, 369],
       [270, 271, 272, 273, 274]])

In [9]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])